services:
  - type: web
    name: warehouse-management-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      NODE_ENV: production
      DATABASE_URL: your_database_url_here
      SECRET_KEY: your_secret_key_here
    autoDeploy: true